### ISSUE TITLE
Auto-generate version hash when loading fzero.css

### ISSUE THREAD

**Issue by JoselleAstrid** [fzerocentral/fzerocentral#14]
About this part of the [base.html template](https://github.com/fzerocentral/fzerocentral/blob/ba1a9c3abd940f5a5e7551f2c6560767703780de/templates/base.html):

`<link rel="stylesheet" href="fzero.css?523d8f4eb1431ecf363ee77c370b2b7cf9de8cb2">`

I assume that 523d... hash is there to tell browsers to reload the CSS file instead of using an outdated cached version. Ideally, that hash would automatically change whenever fzero.css's content is updated (and would not change otherwise), without requiring us to hard-code the hash.

We could put the CSS file's date-modified timestamp as the hash. But it'd be annoying to force every call of `$template->render()` to pass in this timestamp, so perhaps this way would call for a bit of refactoring.

**Comment by hugopeixoto** [comment]
I have this file that I apparently didn't commit to the repository that updates the hashes:

```ruby
#!/usr/bin/env ruby

require 'digest/sha1'

files = %w[
  templates/base.html
]

contents = files.map {|f| [f, File.read(f)]}.to_h

%w[fzero].each do |file|
  checksum = Digest::SHA1.hexdigest(File.read("public/#{file}.css"))
  contents.each do |_, body|
    body.gsub!(
      /"#{file}\.css.*"/,
      "\"#{file}.css?#{checksum}\""
    )
  end
end

contents.each do |name, body|
  File.write(name, body)
end
```

I wrote it in ruby (because that's what I'm familiar with) which is why I didn't commit it.
It could be ported to php, maybe? I was running it manually whenever I did a change, though.

**Comment by JoselleAstrid** [comment]
Ah okay, good to know where the existing hash comes from. Yeah, either a hexdigest of the contents, or a modify-timestamp, either should work I think.

**Comment by JoselleAstrid** [comment]
Done in PR #18 (using modified time).
